### ISSUE TITLE
Don't track node_modules

### ISSUE THREAD

**Issue by JVMartin** [scott-pickthorn/TopPredictions#1]
Howdy!

Just a heads up, don't commit/track your node_modules folder.  You should commit your package.json, but not your node_modules (they are simply installed packages).

You can remedy this by adding `/node_modules` to your .gitignore and then:

``` BASH
git rm --cached -r node_modules
git commit -m "Removing node_modules from tracking"
```

**Comment by scott-pickthorn** [comment]
Thanks for the help! I removed the node_modules and added it to my git ignore

**Comment by JVMartin** [comment]
For sure!

Nice choice of languages and project idea, btw!  Looking forward to seeing it.  :)

**Comment by JVMartin** [comment]
Ack, also it looks like this issue might not be as black and white as I suspected... evidently some people are concerned with the longevity of npm and are committing their node_modules folder out of paranoia.  I prefer to keep outside packages and dependencies out of my repositories, but I may be out of line in recommending others do the same.

Crazy discussions about it:
http://stackoverflow.com/questions/11459475/should-i-check-in-node-modules-to-git-when-creating-a-node-js-app-on-heroku
http://stackoverflow.com/questions/18128863/should-node-modules-folder-be-included-in-the-git-repository

**Comment by scott-pickthorn** [comment]
I think it will be fine removing it seems like the right thing to do. thanks for the help!
